apiVersion: v1
kind: Service
metadata:
  labels:
    name: mglarry-app
  name: mglarry-app-svc
  namespace: dev
spec:
  type: LoadBalancer
  selector:
    app: mglarry-app
  ports:
  - name: http
    protocol: TCP
    port: 3000
    #nodePort: 30001
    targetPort: 3000
